### Vaibhav kumar 

### rollno 19

# Cross Validation 

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import KFold,StratifiedKFold,LeaveOneOut,ShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score,confusion_matrix

In [2]:
iris=pd.read_csv("D:\\vk\\TRIM 3\\ML\\DATASET\\iris.csv")

In [3]:
iris

Sepal length  Sepal width  Petal length  Petal width           Class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
iris.dtypes

Sepal length    float64
Sepal width     float64
Petal length    float64
Petal width     float64
Class            object
dtype: object

In [5]:
features = iris[['Sepal length','Sepal width','Petal length','Petal width']].values
classes = iris['Class'].values

In [6]:
#kfold cross validation technique
kf=KFold(n_splits=5,random_state=1,shuffle=True)
#stratified kfold cross validation technique
skf=StratifiedKFold(n_splits=5)
#Leaveoneout cross validation technique
loocv=LeaveOneOut()
#shuffle split cross validation technique
shcv=ShuffleSplit()

In [7]:
#evaluating the data sets with kfold and Decision tree classifier
dst=DecisionTreeClassifier()
scores=cross_val_score(dst,features,classes,scoring='accuracy',cv=kf) #kf is kFold
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))#this will give avg of  acc
print(scores) # this will give accuracy for 5 splits

Accuarcy using Decision Tree:94.00 %
[0.96666667 0.96666667 0.96666667 0.93333333 0.86666667]


In [8]:
#evaluating the data sets with kfold and Decision tree classifier
nb=GaussianNB()
scores=cross_val_score(nb,features,classes,scoring='accuracy',cv=kf)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))#this will give avg of  acc
print(scores) # this will give accuracy for 5 splits

Accuarcy using Decision Tree:95.33 %
[0.96666667 0.96666667 1.         0.9        0.93333333]


In [9]:
#evaluating the data sets with kfold and Decision tree classifier
svm=SVC()
scores=cross_val_score(svm,features,classes,scoring='accuracy',cv=kf)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))#this will give avg of  acc
print(scores) # this will give accuracy for 5 splits

Accuarcy using Decision Tree:94.67 %
[0.96666667 0.93333333 0.9        0.96666667 0.96666667]


In [10]:
#evaluating the data sets with kfold and Decision tree classifier
knn=KNeighborsClassifier()
scores=cross_val_score(knn,features,classes,scoring='accuracy',cv=kf)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))#this will give avg of  acc
print(scores) # this will give accuracy for 5 splits

Accuarcy using Decision Tree:95.33 %
[1.         0.96666667 0.9        0.93333333 0.96666667]


# Evaluating Dataset using Stratified Kfold

In [11]:
#evaluating the data sets with stratified kfold and Decision tree classifier
scores=cross_val_score(dst,features,classes,scoring='accuracy',cv=skf)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:96.67 %
[0.96666667 0.96666667 0.9        1.         1.        ]


In [12]:
#evaluating the data sets with stratified kfold and Naive bayes
scores=cross_val_score(nb,features,classes,scoring='accuracy',cv=skf)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:95.33 %
[0.93333333 0.96666667 0.93333333 0.93333333 1.        ]


In [13]:
#evaluating the data sets with stratified kfold and SVM classifier
scores=cross_val_score(svm,features,classes,scoring='accuracy',cv=skf)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:96.67 %
[0.96666667 0.96666667 0.96666667 0.93333333 1.        ]


In [14]:
#evaluating the data sets with stratified kfold and knn classifier
scores=cross_val_score(knn,features,classes,scoring='accuracy',cv=skf)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:97.33 %
[0.96666667 1.         0.93333333 0.96666667 1.        ]


# leave one out 

In [15]:
#evaluating the data sets with stratified kfold and Decision tree classifier
scores=cross_val_score(dst,features,classes,scoring='accuracy',cv=loocv)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:96.00 %
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [16]:
#evaluating the data sets with stratified kfold and Naive bayes
scores=cross_val_score(nb,features,classes,scoring='accuracy',cv=loocv)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:95.33 %
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [17]:
#evaluating the data sets with stratified kfold and SVM classifier
scores=cross_val_score(svm,features,classes,scoring='accuracy',cv=loocv)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:96.67 %
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


In [18]:
#evaluating the data sets with stratified kfold and knn classifier
scores=cross_val_score(knn,features,classes,scoring='accuracy',cv=loocv)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:96.67 %
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]


# shuffle 

In [23]:
#evaluating the data sets with stratified kfold and Decision tree classifier
scores=cross_val_score(dst,features,classes,scoring='accuracy',cv=shcv)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:97.33 %
[0.93333333 0.93333333 1.         1.         1.         0.93333333
 0.93333333 1.         1.         1.        ]


In [24]:
#evaluating the data sets with stratified kfold and Naive bayes
scores=cross_val_score(nb,features,classes,scoring='accuracy',cv=shcv)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:94.67 %
[1.         0.93333333 1.         0.8        1.         1.
 0.86666667 1.         1.         0.86666667]


In [25]:
#evaluating the data sets with stratified kfold and SVM classifier
scores=cross_val_score(svm,features,classes,scoring='accuracy',cv=shcv)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:94.67 %
[1.         0.8        0.93333333 0.93333333 1.         0.93333333
 1.         1.         0.93333333 0.93333333]


In [26]:
#evaluating the data sets with stratified kfold and knn classifier
scores=cross_val_score(knn,features,classes,scoring='accuracy',cv=shcv)
print("Accuarcy using Decision Tree:%.2f %%"%(scores.mean()*100))
print(scores)

Accuarcy using Decision Tree:97.33 %
[0.93333333 1.         1.         1.         0.86666667 1.
 1.         1.         0.93333333 1.        ]
